export const languageSet: { [key: string]: { [key: string]: string } } = {
  en: {
    buys: "buys",
    pays: "pays",
    add: "add",
    update: "update",
    updating: "updating",
    delete: "delete",
    deleting: "deleting",
    debets: "debets",
    credits: "credits",
    settings: "settings",
    from: "from",
    for: "for",
    name: "name",
    currency: "currency",
    datetime: "datetime",
    amount: "amount",
    tags: "tags",
    tag: "tag",
    color: "color",
    period: "period",
    start: "start",
    end: "end",
    filter: "filter",
    search: "search",
    stat: "stat",
    sum: "sum",
    all: "all",
    amounts: "amounts",
    close: "close",
    colors: "colors",
    main: "main",
    currencies: "currencies",
    default: "default",
    new: "new",
    base: "base",
    change: "change",
    current: "current",
    load: "load",
    db: "db",
    download: "download",
    upload: "upload",
    page: "page",
    items: "items",
    per: "per",
    payments: "payments",
    set: "set",
    pages: "pages",
    ui: "ui",
    languages: "languages",
    the_number_of_elements_per_payments_page:
      "the number of elements per payments page",
    set_the_number_of_elements: "set the number of elements",
    main_color: "main color",
    change_main_color: "change main color",
    delete_currency: "delete currency",
    add_currency: "add currency",
    new_currency: "new currency",
    change_base: "change base",
    current_base: "current base",
    name_for_new_base: "name for new base",
    add_base: "add base",
    exist_bases: "exist bases",
    base_changed: "Base changed",
    delete_base: "delete base",
    download_data: "download data",
    data_uploaded: "data uploaded",
    manage_data: "manage data",
    components: "components",
    add_tag: "add tag",
    reset_period: "reset period",
    done: "done",
    adding: "adding",
    exchange_rate: "exchange rate",
    reset_filter: "reset filter",
    menu: "menu",
    manage_base: "manage base",
    update_tag: "update tag",
    manage_tags: "manage tags",
    stat_tags: "stat tags",
    help: "help",
    about_app: "about app",
    about_app1:
      "This is intuitive app for self manage your finance. All your data is saving in your device. This app not nedded to internet for work.",
    about_app2:
      "Buys means your pays (costs) for grociers, services, items and etc.",
    about_app3:
      "Pays means your incoming money like salary, gifts, credit money and etc.",
    about_app4:
      "Debets means your debet account in bank (or somewere) or your cash.",
    about_app5:
      "Credits means your credit acount in bank or your debts someone.",
    about_app6: "In settings page you can:",
    about_app7: "set main color",
    about_app8: "change language",
    about_app9: "set default currency and add or delete currencies",
    about_app10:
      "change number of view items on Buys page and Pays page (this affects the loading speed of these pages)",
    about_app11: "manage your tags",
    about_app12: "add new bases and to switch between bases",
    about_app13:
      "save your data in JSON or upload data from file (this can will be needed if you want to transfer your data to another device)",
    need_help: "need help?",
    need_help1:
      "If you have advice on this app or encounter an error - send me an email:",
  },
  by: {
    buys: "пакупкі",
    pays: "выплаты",
    add: "дадаць",
    update: "аднавіць",
    updating: "аднаўляем",
    delete: "выдаліць",
    deleting: "выдаляем",
    debets: "дэбет",
    credits: "крэдыт",
    settings: "налады",
    from: "адкуль",
    for: "куды",
    name: "імя",
    currency: "валюта",
    datetime: "дата і час",
    amount: "кошт",
    tags: "тэгі",
    tag: "тэг",
    color: "колер",
    period: "перыяд",
    start: "пачатак",
    end: "канец",
    filter: "фільтр",
    search: "пошук",
    stat: "статыстыка",
    sum: "сума",
    all: "усе",
    amounts: "кошты",
    close: "закрыць",
    colors: "колеры",
    main: "галоўны",
    currencies: "валюты",
    default: "прадвызначана",
    new: "новая",
    base: "база",
    change: "змяніць",
    current: "актуальная",
    load: "загрузкі",
    db: "бд",
    download: "спампаваць",
    upload: "загрузіць",
    page: "страніца",
    items: "элементы",
    per: "на",
    payments: "плацяжы",
    set: "усталяваць",
    pages: "старонкі",
    ui: "інтэрфейс",
    languages: "мовы",
    the_number_of_elements_per_payments_page:
      "колькасць элементаў на старонцы плацяжоў",
    set_the_number_of_elements: "усталяваць колькасць элементаў",
    main_color: "галоўны колер",
    change_main_color: "змяніць галоўны колер",
    delete_currency: "выдаліць валюту",
    add_currency: "дадаць валюту",
    new_currency: "новая валюта",
    change_base: "змяніць базу",
    current_base: "актуальная база",
    name_for_new_base: "імя для новай базы",
    add_base: "дадаць базу",
    exist_bases: "існуючыя базы",
    base_changed: "база зменена",
    delete_base: "выдаліць базу",
    download_data: "спампаваць данныя",
    data_uploaded: "данныя загружаны",
    upload_data: "загрузіць данныя",
    manage_data: "кіраванне даннымі",
    components: "кампаненты",
    add_tag: "дадаць тэг",
    reset_period: "скінуць перыяд",
    done: "скончана",
    adding: "дадаем",
    exchange_rate: "абменны курс",
    reset_filter: "скінуць фільтр",
    menu: "меню",
    manage_base: "кіраванне базамі",
    update_tag: "аднавіць тэг",
    manage_tags: "кіраванне тэгамі",
    stat_tags: "статыстыка тэгаў",
    help: "дапамога",
    about_app: "пра праграму",
    about_app1:
      "Гэта інтуітыўна зразумелая праграма для самастойнага кіравання сваімі фінансамі. Усе вашы даныя захоўваюцца на вашай прыладзе. Праграме не патрэбен Інтэрнэт для працы",
    about_app2:
      "Пакупкі азначае вашу аплату (выдаткі) за бакалейшчыкаў, паслугі, тавары і г.д.",
    about_app3:
      "Выплаты азначае вашы ўваходныя грошы, такія як зарплата, падарункі, крэдытныя грошы і г.д.",
    about_app4:
      "Дэбет азначае ваш дэбетавы рахунак у банку (ці дзе-небудзь яшчэ) або наяўныя грошы.",
    about_app5:
      "Крэдыты азначаюць ваш крэдытны рахунак у банку або вашы даўгі камусьці",
    about_app6: "На старонцы налад вы можаце:",
    about_app7: "усталяваць асноўны колер",
    about_app8: "змяніць мову",
    about_app9: "усталяваць стандартную валюту і дадаць або выдаліць валюты",
    about_app10:
      "змяніць колькасць тавараў для прагляду на старонках Пакупкі і Выплаты (гэта ўплывае на хуткасць загрузкі гэтых старонак)",
    about_app11: "кіраваць сваімі тэгамі",
    about_app12: "дадаць новыя базы і пераключыцца паміж базамі",
    about_app13:
      "захаваць свае даныя ў JSON або загрузіць даныя з файла (гэта можа спатрэбіцца, калі вы хочаце перанесці даныя на іншую прыладу)",
    need_help: "патрабуецца дапамога?",
    need_help1:
      "Калі ў вас ёсць парады па гэтай праграме або вы сутыкнуліся з памылкай - дашліце мне ліст:",
  },
};
