import { create } from "zustand";
import { persist } from "zustand/middleware";
import { LanguageStore } from "../interfaces";
import { name as appName } from "../../package.json";

const textes: { [key: string]: { [key: string]: string } } = {
  en: {
    buys: "buys",
    pays: "pays",
    add: "add",
    update: "update",
    updating: "updating",
    delete: "delete",
    deleting: "deleting",
    debets: "debets",
    credits: "credits",
    settings: "settings",
    from: "from",
    for: "for",
    name: "name",
    currency: "currency",
    datetime: "datetime",
    amount: "amount",
    tags: "tags",
    tag: "tag",
    color: "color",
    period: "period",
    start: "start",
    end: "end",
    filter: "filter",
    search: "search",
    stat: "stat",
    sum: "sum",
    all: "all",
    amounts: "amounts",
    close: "close",
    colors: "colors",
    main: "main",
    currencies: "currencies",
    default: "default",
    new: "new",
    base: "base",
    change: "change",
    current: "current",
    load: "load",
    db: "db",
    download: "download",
    upload: "upload",
    page: "page",
    items: "items",
    per: "per",
    payments: "payments",
    set: "set",
    pages: "pages",
    ui: "ui",
    languages: "languages",
    the_number_of_elements_per_payments_page:
      "the number of elements per payments page",
    set_the_number_of_elements: "set the number of elements",
    main_color: "main color",
    change_main_color: "change main color",
    delete_currency: "delete currency",
    add_currency: "add currency",
    new_currency: "new currency",
    change_base: "change base",
    current_base: "current base",
    name_for_new_base: "name for new base",
    add_base: "add base",
    exist_bases: "exist bases",
    base_changed: "Base changed",
    delete_base: "delete base",
    download_data: "download data",
    data_uploaded: "data uploaded",
    manage_data: "manage data",
    components: "components",
    add_tag: "add tag",
    reset_period: "reset period",
    done: "done",
    adding: "adding",
    exchange_rate: "exchange rate",
    reset_filter: "reset filter",
    menu: "menu",
  },
  by: {
    buys: "пакупкі",
    pays: "выплаты",
    add: "дадаць",
    update: "аднавіць",
    updating: "аднаўляем",
    delete: "выдаліць",
    deleting: "выдаляем",
    debets: "дэбет",
    credits: "крэдзіт",
    settings: "налады",
    from: "адкуль",
    for: "куды",
    name: "імя",
    currency: "валюта",
    datetime: "дата і час",
    amount: "кошт",
    tags: "тэгі",
    tag: "тэг",
    color: "колер",
    period: "перыяд",
    start: "пачатак",
    end: "канец",
    filter: "фільтр",
    search: "пошук",
    stat: "статыстыка",
    sum: "сума",
    all: "усе",
    amounts: "кошты",
    close: "закрыць",
    colors: "колеры",
    main: "галоўны",
    currencies: "валюты",
    default: "прадвызначана",
    new: "новая",
    base: "база",
    change: "змяніць",
    current: "актуальная",
    load: "загрузкі",
    db: "бд",
    download: "спампаваць",
    upload: "загрузіць",
    page: "страніца",
    items: "элементы",
    per: "на",
    payments: "плацяжы",
    set: "усталяваць",
    pages: "старонкі",
    ui: "інтэрфейс",
    languages: "мовы",
    the_number_of_elements_per_payments_page:
      "колькасць элементаў на старонцы плацяжоў",
    set_the_number_of_elements: "усталяваць колькасць элементаў",
    main_color: "галоўны колер",
    change_main_color: "змяніць галоўны колер",
    delete_currency: "выдаліць валюту",
    add_currency: "дадаць валюту",
    new_currency: "новая валюта",
    change_base: "змяніць базу",
    current_base: "актуальная база",
    name_for_new_base: "імя для новай базы",
    add_base: "дадаць базу",
    exist_bases: "існуючыя базы",
    base_changed: "база зменена",
    delete_base: "выдаліць базу",
    download_data: "спампаваць данныя",
    data_uploaded: "данныя загружаны",
    upload_data: "загрузіць данныя",
    manage_data: "Кіраванне даннымі",
    components: "кампаненты",
    add_tag: "дадаць тэг",
    reset_period: "скінуць перыяд",
    done: "скончана",
    adding: "дадаем",
    exchange_rate: "абменны курс",
    reset_filter: "скінуць фільтр",
    menu: "меню",
  },
};

export const useLanguageStore = create<LanguageStore>()(
  persist(
    (set, get) => {
      return {
        currentLanguage: "en",
        languages: ["en", "by"],
        setCurrentLanguage: (lang) => set({ currentLanguage: lang }),
        textes: () => textes[`${get().currentLanguage}`],
      };
    },
    {
      name: `${appName}-languages`,
    }
  )
);
