export const languageSet: { [key: string]: { [key: string]: string } } = {
  en: {
    buys: "buys",
    pays: "pays",
    add: "add",
    update: "update",
    updating: "updating",
    delete: "delete",
    deleting: "deleting",
    debits: "debits",
    credits: "credits",
    settings: "settings",
    from: "from",
    for: "for",
    name: "name",
    currency: "currency",
    datetime: "datetime",
    amount: "amount",
    tags: "tags",
    tag: "tag",
    color: "color",
    period: "period",
    start: "start",
    end: "end",
    filter: "filter",
    search: "search",
    stat: "stat",
    sum: "sum",
    all: "all",
    amounts: "amounts",
    close: "close",
    colors: "colors",
    main: "main",
    currencies: "currencies",
    default: "default",
    new: "new",
    base: "base",
    change: "change",
    current: "current",
    load: "load",
    db: "db",
    download: "download",
    upload: "upload",
    upload_data: "upload data",
    page: "page",
    items: "items",
    per: "per",
    payments: "payments",
    set: "set",
    pages: "pages",
    ui: "ui",
    languages: "languages",
    the_number_of_elements_per_payments_page:
      "the number of elements per payments page",
    set_the_number_of_elements: "set the number of elements",
    main_color: "main color",
    change_main_color: "change main color",
    delete_currency: "delete currency",
    add_currency: "add currency",
    new_currency: "new currency",
    change_base: "change base",
    current_base: "current base",
    name_for_new_base: "name for new base",
    add_base: "add base",
    exist_bases: "exist bases",
    base_changed: "Base changed",
    delete_base: "delete base",
    download_data: "download data",
    data_uploaded: "data uploaded",
    manage_data: "manage data",
    components: "components",
    add_tag: "add tag",
    reset_period: "reset period",
    done: "done",
    adding: "adding",
    exchange_rate: "exchange rate",
    reset_filter: "reset filter",
    menu: "menu",
    manage_base: "manage base",
    update_tag: "update tag",
    manage_tags: "manage tags",
    stat_tags: "stat tags",
    help: "help",
    about_app: "about app",
    about_app1:
      "This is intuitive app for self manage your finance. All your data is saving in your device. This app not nedded to internet for work.",
    about_app2:
      "Buys means your pays (costs) for grociers, services, items, credits and etc.",
    about_app3:
      "Pays means your incoming money like salary, gifts, credit money and etc.",
    about_app4: "Debits means your debits acount or your cash.",
    about_app5:
      "Credits means your credits, installments or your debts someone.",
    about_app6: "Settings allow you to:",
    about_app7: "set main color",
    about_app8: "change language",
    about_app9: "set default currency and add or delete currencies",
    about_app10:
      "change number of view items on Buys page and Pays page (this affects the loading speed of these pages)",
    about_app11: "manage your tags",
    about_app12: "add new bases and to switch between bases",
    about_app13:
      "save your data in JSON or upload data from file (this can will be needed if you want to transfer your data to another device)",
    need_help: "need help?",
    need_help1:
      "If you have advice on this app or encounter an error - send me an email:",
    search_by_sources: "search by sources",
    search_by_from_or_for: "search by from or for",
    auto_add_tags: "Auto add tags",
  },
  be: {
    buys: "пакупкі",
    pays: "выплаты",
    add: "дадаць",
    update: "аднавіць",
    updating: "аднаўляем",
    delete: "выдаліць",
    deleting: "выдаляем",
    debits: "дэбіты",
    credits: "крэдыты",
    settings: "налады",
    from: "адкуль",
    for: "куды",
    name: "імя",
    currency: "валюта",
    datetime: "дата і час",
    amount: "кошт",
    tags: "тэгі",
    tag: "тэг",
    color: "колер",
    period: "перыяд",
    start: "пачатак",
    end: "канец",
    filter: "фільтр",
    search: "пошук",
    stat: "статыстыка",
    sum: "сума",
    all: "усе",
    amounts: "кошты",
    close: "закрыць",
    colors: "колеры",
    main: "галоўны",
    currencies: "валюты",
    default: "прадвызначана",
    new: "новая",
    base: "база",
    change: "змяніць",
    current: "актуальная",
    load: "загрузкі",
    db: "бд",
    download: "спампаваць",
    upload: "загрузіць",
    upload_data: "загрузіць дадзеныя",
    page: "страніца",
    items: "элементы",
    per: "на",
    payments: "плацяжы",
    set: "усталяваць",
    pages: "старонкі",
    ui: "інтэрфейс",
    languages: "мовы",
    the_number_of_elements_per_payments_page:
      "колькасць элементаў на старонцы плацяжоў",
    set_the_number_of_elements: "усталяваць колькасць элементаў",
    main_color: "галоўны колер",
    change_main_color: "змяніць галоўны колер",
    delete_currency: "выдаліць валюту",
    add_currency: "дадаць валюту",
    new_currency: "новая валюта",
    change_base: "змяніць базу",
    current_base: "актуальная база",
    name_for_new_base: "імя для новай базы",
    add_base: "дадаць базу",
    exist_bases: "існуючыя базы",
    base_changed: "база зменена",
    delete_base: "выдаліць базу",
    download_data: "спампаваць данныя",
    data_uploaded: "данныя загружаны",
    manage_data: "кіраванне даннымі",
    components: "кампаненты",
    add_tag: "дадаць тэг",
    reset_period: "скінуць перыяд",
    done: "скончана",
    adding: "дадаем",
    exchange_rate: "абменны курс",
    reset_filter: "скінуць фільтр",
    menu: "меню",
    manage_base: "кіраванне базамі",
    update_tag: "аднавіць тэг",
    manage_tags: "кіраванне тэгамі",
    stat_tags: "статыстыка тэгаў",
    help: "дапамога",
    about_app: "пра праграму",
    about_app1:
      "Гэта інтуітыўна зразумелая праграма для самастойнага кіравання сваімі фінансамі. Усе вашы даныя захоўваюцца на вашай прыладзе. Праграме не патрэбен Інтэрнэт для працы",
    about_app2:
      "Пакупкі азначае вашу аплату (выдаткі) за ежу, паслугі, тавары, крэдыты і г.д.",
    about_app3:
      "Выплаты азначае вашы ўваходныя грошы, такія як зарплата, падарункі, крэдытныя грошы і г.д.",
    about_app4: "Дэбіты азначае вашы дэбітавы рахункі або наяўныя грошы.",
    about_app5:
      "Крэдыты азначаюць вашы крэдыты, растэрміноўкі або вашы даўгі камусьці",
    about_app6: "Налады дазваляюць вам:",
    about_app7: "усталяваць асноўны колер",
    about_app8: "змяніць мову",
    about_app9: "усталяваць стандартную валюту і дадаць або выдаліць валюты",
    about_app10:
      "змяніць колькасць тавараў для прагляду на старонках Пакупкі і Выплаты (гэта ўплывае на хуткасць загрузкі гэтых старонак)",
    about_app11: "кіраваць сваімі тэгамі",
    about_app12: "дадаць новыя базы і пераключыцца паміж базамі",
    about_app13:
      "захаваць свае даныя ў JSON або загрузіць даныя з файла (гэта можа спатрэбіцца, калі вы хочаце перанесці даныя на іншую прыладу)",
    need_help: "патрабуецца дапамога?",
    need_help1:
      "Калі ў вас ёсць парады па гэтай праграме або вы сутыкнуліся з памылкай - дашліце мне ліст:",
    search_by_sources: "пошук па крыніцах",
    search_by_from_or_for: "пошук па адкуль або куды",
    auto_add_tags: "Аўтаматычна дадаваць тэгі",
  },
  uk: {
    buys: "покупки",
    pays: "платежі",
    add: "додати",
    update: "оновити",
    updating: "оновлення",
    delete: "видалити",
    deleting: "видалення",
    debits: "дебети",
    credits: "кредити",
    settings: "налаштування",
    from: "від",
    for: "для",
    name: "ім'я",
    currency: "валюта",
    datetime: "дата і час",
    amount: "сума",
    tags: "теги",
    tag: "тег",
    color: "колір",
    period: "період",
    start: "початок",
    end: "кінець",
    filter: "фільтр",
    search: "пошук",
    stat: "статистика",
    sum: "сума",
    all: "всі",
    amounts: "суми",
    close: "закрити",
    colors: "кольори",
    main: "основний",
    currencies: "валюти",
    default: "за замовчуванням",
    new: "новий",
    base: "база",
    change: "змінити",
    current: "поточний",
    load: "завантажити",
    db: "база даних",
    download: "завантажити",
    upload: "завантажити",
    upload_data: "завантажити дані",
    page: "сторінка",
    items: "елементи",
    per: "на",
    payments: "платежі",
    set: "встановити",
    pages: "сторінки",
    ui: "інтерфейс користувача",
    languages: "мови",
    the_number_of_elements_per_payments_page:
      "кількість елементів на сторінці платежів",
    set_the_number_of_elements: "встановити кількість елементів",
    main_color: "основний колір",
    change_main_color: "змінити основний колір",
    delete_currency: "видалити валюту",
    add_currency: "додати валюту",
    new_currency: "нова валюта",
    change_base: "змінити базу",
    current_base: "поточна база",
    name_for_new_base: "ім'я для нової бази",
    add_base: "додати базу",
    exist_bases: "існуючі бази",
    base_changed: "базу змінено",
    delete_base: "видалити базу",
    download_data: "завантажити дані",
    data_uploaded: "дані завантажено",
    manage_data: "керувати даними",
    components: "компоненти",
    add_tag: "додати тег",
    reset_period: "скинути період",
    done: "готово",
    adding: "додавання",
    exchange_rate: "обмінний курс",
    reset_filter: "скинути фільтр",
    menu: "меню",
    manage_base: "керувати базою",
    update_tag: "оновити тег",
    manage_tags: "керувати тегами",
    stat_tags: "статистика тегів",
    help: "допомога",
    about_app: "про додаток",
    about_app1:
      "Це інтуїтивно зрозумілий додаток для самостійного управління фінансами. Всі ваші дані зберігаються на вашому пристрої. Для роботи цьому додатку не потрібен інтернет.",
    about_app2:
      "Покупки означають ваші витрати на продукти, послуги, товари, кредити тощо.",
    about_app3:
      "Платежі означають ваші надходження, такі як зарплата, подарунки, кредитні гроші тощо.",
    about_app4: "Дебети означають ваш дебетовий рахунок або готівку.",
    about_app5: "Кредити означають ваші кредити, розстрочки або борги комусь.",
    about_app6: "Налаштування дозволяють вам",
    about_app7: "встановити основний колір",
    about_app8: "змінити мову",
    about_app9:
      "встановити валюту за замовчуванням і додати або видалити валюти",
    about_app10:
      "змінити кількість відображуваних елементів на сторінці Покупок і сторінці Платежів (це впливає на швидкість завантаження цих сторінок)",
    about_app11: "керувати вашими тегами",
    about_app12: "додавати нові бази і переключатися між базами",
    about_app13:
      "зберігати ваші дані у форматі JSON або завантажувати дані з файлу (це може знадобитися, якщо ви хочете перенести ваші дані на інший пристрій)",
    need_help: "потрібна допомога?",
    need_help1:
      "Якщо у вас є поради щодо цього додатку або ви зіткнулися з помилкою - надішліть мені електронний лист",
    search_by_sources: "пошук за джерелами",
    search_by_from_or_for: "пошук за від або для",
    auto_add_tags: "Автоматичне додавання тегів",
  },
  zh: {
    buys: "购买",
    pays: "支付",
    add: "添加",
    update: "更新",
    updating: "更新中",
    delete: "删除",
    deleting: "删除中",
    debits: "借记",
    credits: "信用",
    settings: "设置",
    from: "从",
    for: "为",
    name: "名称",
    currency: "货币",
    datetime: "日期和时间",
    amount: "金额",
    tags: "标签",
    tag: "标签",
    color: "颜色",
    period: "期间",
    start: "开始",
    end: "结束",
    filter: "过滤",
    search: "搜索",
    stat: "统计",
    sum: "总和",
    all: "所有",
    amounts: "金额",
    close: "关闭",
    colors: "颜色",
    main: "主要",
    currencies: "货币",
    default: "默认",
    new: "新",
    base: "基础",
    change: "更改",
    current: "当前",
    load: "加载",
    db: "数据库",
    download: "下载",
    upload: "上传",
    upload_data: "上传数据",
    page: "页面",
    items: "项目",
    per: "每",
    payments: "支付",
    set: "设置",
    pages: "页面",
    ui: "用户界面",
    languages: "语言",
    the_number_of_elements_per_payments_page: "每个支付页面的元素数量",
    set_the_number_of_elements: "设置元素数量",
    main_color: "主要颜色",
    change_main_color: "更改主要颜色",
    delete_currency: "删除货币",
    add_currency: "添加货币",
    new_currency: "新货币",
    change_base: "更改基础",
    current_base: "当前基础",
    name_for_new_base: "新基础的名称",
    add_base: "添加基础",
    exist_bases: "现有基础",
    base_changed: "基础已更改",
    delete_base: "删除基础",
    download_data: "下载数据",
    data_uploaded: "数据已上传",
    manage_data: "管理数据",
    components: "组件",
    add_tag: "添加标签",
    reset_period: "重置期间",
    done: "完成",
    adding: "添加中",
    exchange_rate: "汇率",
    reset_filter: "重置过滤器",
    menu: "菜单",
    manage_base: "管理基础",
    update_tag: "更新标签",
    manage_tags: "管理标签",
    stat_tags: "标签统计",
    help: "帮助",
    about_app: "关于应用",
    about_app1:
      "这是一个直观的应用程序，用于自我管理您的财务。所有数据都保存在您的设备中。此应用程序不需要互联网即可工作。",
    about_app2: "购买意味着您的支出（费用）用于杂货、服务、物品、信用等。",
    about_app3: "支付意味着您的收入，如工资、礼物、信用资金等。",
    about_app4: "借记意味着您的借记账户或现金。",
    about_app5: "信用意味着您的信用、分期付款或您欠他人的债务。",
    about_app6: "设置允许您：",
    about_app7: "设置主要颜色",
    about_app8: "更改语言",
    about_app9: "设置默认货币并添加或删除货币",
    about_app10:
      "更改购买页面和支付页面上显示的项目数量（这会影响这些页面的加载速度）",
    about_app11: "管理您的标签",
    about_app12: "添加新基础并在基础之间切换",
    about_app13:
      "将您的数据保存为JSON格式或从文件中上传数据（如果您想将数据转移到另一台设备上，这可能会需要）",
    need_help: "需要帮助？",
    need_help1: "如果您对这个应用有建议或遇到错误，请发送电子邮件给我：",
    search_by_sources: "按来源搜索",
    search_by_from_or_for: "按“发件人”或“收件人”搜索",
    auto_add_tags: "自动添加标签",
  },
  ja: {
    buys: "購入",
    pays: "支払い",
    add: "追加",
    update: "更新",
    updating: "更新中",
    delete: "削除",
    deleting: "削除中",
    debits: "デビット",
    credits: "クレジット",
    settings: "設定",
    from: "から",
    for: "ため",
    name: "名前",
    currency: "通貨",
    datetime: "日付と時間",
    amount: "金額",
    tags: "タグ",
    tag: "タグ",
    color: "色",
    period: "期間",
    start: "開始",
    end: "終了",
    filter: "フィルター",
    search: "検索",
    stat: "統計",
    sum: "合計",
    all: "すべて",
    amounts: "金額",
    close: "閉じる",
    colors: "色",
    main: "メイン",
    currencies: "通貨",
    default: "デフォルト",
    new: "新しい",
    base: "ベース",
    change: "変更",
    current: "現在",
    load: "ロード",
    db: "データベース",
    download: "ダウンロード",
    upload: "アップロード",
    upload_data: "データのアップロード",
    page: "ページ",
    items: "アイテム",
    per: "ごとに",
    payments: "支払い",
    set: "設定",
    pages: "ページ",
    ui: "ユーザーインターフェース",
    languages: "言語",
    the_number_of_elements_per_payments_page: "支払いページごとの要素数",
    set_the_number_of_elements: "要素数を設定",
    main_color: "メインカラー",
    change_main_color: "メインカラーを変更",
    delete_currency: "通貨を削除",
    add_currency: "通貨を追加",
    new_currency: "新しい通貨",
    change_base: "ベースを変更",
    current_base: "現在のベース",
    name_for_new_base: "新しいベースの名前",
    add_base: "ベースを追加",
    exist_bases: "既存のベース",
    base_changed: "ベースが変更されました",
    delete_base: "ベースを削除",
    download_data: "データをダウンロード",
    data_uploaded: "データがアップロードされました",
    manage_data: "データを管理",
    components: "コンポーネント",
    add_tag: "タグを追加",
    reset_period: "期間をリセット",
    done: "完了",
    adding: "追加中",
    exchange_rate: "為替レート",
    reset_filter: "フィルターをリセット",
    menu: "メニュー",
    manage_base: "ベースを管理",
    update_tag: "タグを更新",
    manage_tags: "タグを管理",
    stat_tags: "タグの統計",
    help: "ヘルプ",
    about_app: "アプリについて",
    about_app1:
      "これは、財務を自己管理するための直感的なアプリです。すべてのデータはデバイスに保存されます。このアプリはインターネットを必要としません。",
    about_app2:
      "購入は、食料品、サービス、アイテム、クレジットなどの費用を意味します。",
    about_app3:
      "支払いは、給与、贈り物、クレジットマネーなどの収入を意味します。",
    about_app4: "デビットは、デビットアカウントまたは現金を意味します。",
    about_app5:
      "クレジットは、クレジット、分割払い、または他人への借金を意味します。",
    about_app6: "設定では次のことができます：",
    about_app7: "メインカラーを設定",
    about_app8: "言語を変更",
    about_app9: "デフォルトの通貨を設定し、通貨を追加または削除",
    about_app10:
      "購入ページと支払いページに表示されるアイテムの数を変更（これにより、これらのページの読み込み速度に影響します）",
    about_app11: "タグを管理",
    about_app12: "新しいベースを追加し、ベース間を切り替え",
    about_app13:
      "データをJSON形式で保存するか、ファイルからデータをアップロード（データを別のデバイスに転送する場合に必要になることがあります）",
    need_help: "助けが必要ですか？",
    need_help1:
      "このアプリに関するアドバイスやエラーが発生した場合は、メールを送信してください：",
    search_by_sources: "ソースから探す",
    search_by_from_or_for: "送信者」または「受信者」で検索",
    auto_add_tags: "自動タグ追加",
  },
  ru: {
    buys: "покупки",
    pays: "платежи",
    add: "добавить",
    update: "обновить",
    updating: "обновление",
    delete: "удалить",
    deleting: "удаление",
    debits: "дебеты",
    credits: "кредиты",
    settings: "настройки",
    from: "от",
    for: "для",
    name: "имя",
    currency: "валюта",
    datetime: "дата и время",
    amount: "сумма",
    tags: "теги",
    tag: "тег",
    color: "цвет",
    period: "период",
    start: "начало",
    end: "конец",
    filter: "фильтр",
    search: "поиск",
    stat: "статистика",
    sum: "сумма",
    all: "все",
    amounts: "суммы",
    close: "закрыть",
    colors: "цвета",
    main: "основной",
    currencies: "валюты",
    default: "по умолчанию",
    new: "новый",
    base: "база",
    change: "изменить",
    current: "текущий",
    load: "загрузить",
    db: "база данных",
    download: "скачать",
    upload: "загрузить",
    upload_data: "загрузить данные",
    page: "страница",
    items: "элементы",
    per: "на",
    payments: "платежи",
    set: "установить",
    pages: "страницы",
    ui: "пользовательский интерфейс",
    languages: "языки",
    the_number_of_elements_per_payments_page:
      "количество элементов на странице платежей",
    set_the_number_of_elements: "установить количество элементов",
    main_color: "основной цвет",
    change_main_color: "изменить основной цвет",
    delete_currency: "удалить валюту",
    add_currency: "добавить валюту",
    new_currency: "новая валюта",
    change_base: "изменить базу",
    current_base: "текущая база",
    name_for_new_base: "имя для новой базы",
    add_base: "добавить базу",
    exist_bases: "существующие базы",
    base_changed: "база изменена",
    delete_base: "удалить базу",
    download_data: "скачать данные",
    data_uploaded: "данные загружены",
    manage_data: "управлять данными",
    components: "компоненты",
    add_tag: "добавить тег",
    reset_period: "сбросить период",
    done: "готово",
    adding: "добавление",
    exchange_rate: "обменный курс",
    reset_filter: "сбросить фильтр",
    menu: "меню",
    manage_base: "управлять базой",
    update_tag: "обновить тег",
    manage_tags: "управлять тегами",
    stat_tags: "статистика тегов",
    help: "помощь",
    about_app: "о приложении",
    about_app1:
      "Это интуитивно понятное приложение для самостоятельного управления финансами. Все ваши данные сохраняются на вашем устройстве. Для работы этому приложению не нужен интернет.",
    about_app2:
      "Покупки означают ваши расходы (затраты) на продукты, услуги, товары, кредиты и т.д.",
    about_app3:
      "Платежи означают ваши поступления, такие как зарплата, подарки, кредитные деньги и т.д.",
    about_app4: "Дебеты означают ваш дебетовый счет или наличные.",
    about_app5: "Кредиты означают ваши кредиты, рассрочки или долги кому-то.",
    about_app6: "Настройки позволяют вам",
    about_app7: "установить основной цвет",
    about_app8: "изменить язык",
    about_app9: "установить валюту по умолчанию и добавить или удалить валюты",
    about_app10:
      "изменить количество отображаемых элементов на странице Покупок и странице Платежей (это влияет на скорость загрузки этих страниц)",
    about_app11: "управлять вашими тегами",
    about_app12: "добавлять новые базы и переключаться между базами",
    about_app13:
      "сохранять ваши данные в формате JSON или загружать данные из файла (это может понадобиться, если вы хотите перенести ваши данные на другое устройство)",
    need_help: "нужна помощь?",
    need_help1:
      "Если у вас есть советы по этому приложению или вы столкнулись с ошибкой - отправьте мне электронное письмо",
    search_by_sources: "поиск по источникам",
    search_by_from_or_for: "поиск по от или для",
    auto_add_tags: "Автоматически добавлять тэги",
  },
};
